name: Docker Build
on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}

jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud Platform SDK and authenticate
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - name: Configure Docker for GCP credential helper
        run: gcloud --quiet auth configure-docker

      - name: Build Docker Image
        run: |
          docker build . -t ${{ env.IMAGE_NAME }}:master-${{ env.GITHUB_SHA_SHORT }}
      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}:master-${{ env.GITHUB_SHA_SHORT }}